// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LichessPerf } from "./LichessPerf";
import type { LichessPlayer } from "./LichessPlayer";

export type LichessPuzzleGame = { id: string, perf: LichessPerf, rated: boolean, players: Array<LichessPlayer>, pgn: string, clock: string, };
