// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LichessPuzzle = { id: string, rating: number, plays: number, solution: Array<string>, themes: Array<string>, initialPly: number, };
