// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LichessPuzzle } from "./LichessPuzzle";
import type { LichessPuzzleGame } from "./LichessPuzzleGame";

export type LichessPuzzleResponse = { game: LichessPuzzleGame, puzzle: LichessPuzzle, };
