// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayerStatistics = { current_elo: number, accuracy: number, time_played: number, games_played: number, win_rate: number, };
